### ISSUE TITLE
Angular 7

### ISSUE THREAD

**Issue by Paul75** [kappys1/angular2-carousel#12]
Hello,

Compatible with Angular 7 ?

thanks

**Comment by Paul75** [comment]
I test and got : 
ERROR in Error during template compile of 'MyHammerConfig'
  Class MyHammerConfig in C:/www/vinsvoyage/client/node_modules/angular2-carousel/src/carousel.module.d.ts extends from a Injectable in another compilation unit without duplicating the decorator
    Please add a Injectable or Pipe or Directive or Component or NgModule decorator to the class.

**Comment by kappys1** [comment]
Sorry but I'm not test yet it in Angular7...

in a few time I want to change all library for solve this kind of problems, thanks for the issue

**Comment by kappys1** [comment]
Hi! you can use ngx-carousel now for Angular 7. New library. same funcionality and it is without Hammer dependency.

https://www.npmjs.com/package/ngx-carousel-lib

https://github.com/kappys1/ngx-carousel
