### ISSUE TITLE
activeIndex does not exist on type

### ISSUE THREAD

**Issue by marcoshier** [kappys1/angular2-carousel#3]
Hi, I'm trying to modify the carousel so that when I reach a certain slide it triggers a text change in another div (a caption).

I figured out, through the API, that i need to set a function like:
`fooIndexActive() {
 if (this.CarouselComp.activeIndex(1)) {
  el.text("foo")
};
}`

but i get the typescript error 'property activeIndex does not exist on type 'CarouselComponent'.
Am I doing something wrong?

**Comment by kappys1** [comment]
Hi!

I think that you have a mistake when you want access to variable. If you see the API, 
`activeIndex` is a number type, not a function, and for access to this variable you shoud access to carousel variable inside your component variable first...

For check it, you can stop with debuger in this sentence and check the status in these moment

Example:
`fooIndexActive() { if (this.CarouselComp.carousel.activeIndex === 1) { el.text("foo") }; }`


However , I see a mistake in my api, in the example. Thanks for all!

I hope that it can help you

**Comment by marcoshier** [comment]
That removes the ts error, but it seems to work only if I add an user interaction (for example "(click)") in the html. Is there a way I can start the function right away at component loading without needing any previous user interaction?

**Comment by kappys1** [comment]
Yes!
If you want start one function when the component is ready you have the angular functions that it fires when all view is loaded or in my component you have the event onReady (See the api for more events)

I do a example for you in [Plunker](https://plnkr.co/edit/CGjrIDTYTmGqlB2eqOyr?p=preview) with onReady event.

I hope help you and if this plugin is useful for you, can you give me a star? you could help me with this a lot . thank

**Comment by marcoshier** [comment]
Now I'm getting another error, and I take the cance to ask for a clarification.
The error I get
` Uncaught TypeError: Cannot read property 'carousel' of undefined`
Therefore I think I don't understand what does 'carousel' represent in the line of code you told me:
`fooIndexActive() { if (this.CarouselComp.carousel.activeIndex === 1) { el.text("foo") }; }`

**Comment by kappys1** [comment]
Are you sure that your `this.CarouselComp` isn't undefined? 

Do you get the component fine?
Just see the [Example](https://plnkr.co/edit/CGjrIDTYTmGqlB2eqOyr?p=preview) and You can see how You can get the component and use the activeIndex Property.

**Comment by marcoshier** [comment]
Sorry that error was due to an older piece of code.

Still, the text change occurs when I use the (click) function but not with (onReady). What might be the problem?

**Comment by kappys1** [comment]
mmm... I don't know why....
See this [example](https://plnkr.co/edit/ATApGM3WlV73jPc0ypZq?p=preview) ( other) , in this case I change the second slide when you click....

**Comment by kappys1** [comment]
@shierone Have you solved the problem?

**Comment by kappys1** [comment]
I close the issue because I think that all is right
