### ISSUE TITLE
Looping not working

### ISSUE THREAD

**Issue by alkaj** [kappys1/angular2-carousel#4]
Hi, I am using this library for a slider and don't know how to make it loop through elements as when I try with the `[loop]="true"` it doesn't change anything.
Is that the right way to activate looping? thanks in advance!

**Comment by kappys1** [comment]
Hi, 

You can see the carousel api here :  https://kappys1.github.io/angular2-carousel/api

In this moment the loop mode is not available, in the next release it will be posible

Thanks!

**Comment by alkaj** [comment]
Ok thanks to you for your quick reaction!
