### ISSUE TITLE
Bug when third item reached

### ISSUE THREAD

**Issue by Neriadok** [kappys1/angular2-carousel#6]
Hi, Good evening,

Before all, congratulations for your carousel, it's awesome. Said this, I have a bug when "touch sliding" to the third of six items.

I've noticed this is because when you apply to the ".carousel" element style="transform: rotateY(-90deg)" the item gets width 0, making imposible to slide again. I'll try to fix it by my own, but would be great if you can help, thanks.

**Comment by kappys1** [comment]
Hi!

Can you show me the bug in a example? For example plunker or jsfiddle.

Thanks

**Comment by Neriadok** [comment]
I've found something that "solves it", changing the angle to 40.

Here you have two captures:

This is second item with deg -45º
![image](https://user-images.githubusercontent.com/11853974/39721572-425ecb6c-5240-11e8-8f6b-b1db0f965de6.png)


This is the third with deg -90º
![image](https://user-images.githubusercontent.com/11853974/39721619-6755a1ca-5240-11e8-91fc-e8c3f1f636c7.png)

The problem is that -90º make the element perpendicular to the screen.

**Comment by kappys1** [comment]
Thanks for the bug!

This is not problem of my library! is problem of hammer, my gesture provider ...if you see the console you can watch the violation error.
https://www.chromestatus.com/feature/5745543795965952
https://stackoverflow.com/questions/39152877/consider-marking-event-handler-as-passive-to-make-the-page-more-responsive
I'm looking more info about this and if is possible solve it as soon of possible.

Thanks so much!

**Comment by Neriadok** [comment]
As far as I see, just given your component [angle]=40, the bug is solved for me (instead of 90deg it comes rotate 80 deg :p).

Any way, in my console there was no bug. Maybe i'm catching it some where,but I'm not sure.

Thanks for your quicks answers ;)

**Comment by kappys1** [comment]
Hi!
Yes, yesterday I found this solution but I think that it is not a good solution for the others users.

Thanks for all and I'm keep investigating for a better solution!

**Comment by kappys1** [comment]
Hi ! I solve it now!
If you cant help me, you can give me a star :P 

enjoy the carousel and thanks for info about the bug
