### ISSUE TITLE
Initially it's not working correctly. But after resizing it's coming perfectly. Why so?

### ISSUE THREAD

**Issue by sruthivarghese15** [kappys1/angular2-carousel#8]
Initially it's not working correctly. But after resizing it's coming perfectly. Why so?

Initial state:
![carousel-2](https://user-images.githubusercontent.com/20354332/41470712-17875528-70cf-11e8-8f65-6ea319cba6a6.PNG)

After resizing:
![carousel-1](https://user-images.githubusercontent.com/20354332/41470737-26a10626-70cf-11e8-9ecb-9f38c8ff7f83.PNG)

My code:

` <carousel-component class="style-carousel" [mode]="'horizontal'" [morePairSlides]="3" [angle]="25" [margin]="-50" #topCarousel style="width: 100%" (onReachEnd)="topCarousel.slideTo(0)">
                <div class="item-carousel" ><button class="btn blue-btn" id="item-1">Ethanol</button> </div >
                <div class="item-carousel" ><button class="btn blue-btn" id="item-2">50% KOH</button></div>
                <div class="item-carousel" ><button class="btn blue-btn" id="item-3">Water</button></div>
                <div class="item-carousel" ><button class="btn blue-btn" id="item-4">3N HCL</button></div>
                <div class="item-carousel" ><button class="btn blue-btn" id="item-5">Hexane</button></div>
                <div class="item-carousel" `><button` class="btn blue-btn" id="item-6">Other</button></div>
              </carousel-component>  `

css:
`.item-carousel div,
.item-carousel .btn{
  height: 100%;
  width: 100%;
}
.item-carousel div{
  background-size: contain;
  background-repeat: no-repeat;
  background-position: center center;
}

.carousel .item-carousel {
border: none;
}

:host carousel-component{
  display: block;
  overflow: hidden;
  padding: 8px 6px;
  width: 50%;
  margin: 0 auto;
  margin-top: 7%;
}
h1{
  font-size: 3vh;
  font-weight: 200;
  color: #1976d2;
}

.item-carousel{
  background-color: rgba(255,255,255,0);
  display: -ms-flexbox!important;
  display: -webkit-flex!important;
  display: flex!important;
  -webkit-flex-direction: row;
  -ms-flex-direction: row;
  flex-direction: row;
  -webkit-flex-wrap: nowrap;
  -ms-flex-wrap: nowrap;
  flex-wrap: nowrap;
  -webkit-justify-content: center;
  -ms-flex-pack: center;
  justify-content: center;
  -webkit-align-content: stretch;
  -ms-flex-line-pack: stretch;
  align-content: stretch;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
  width: 100px!important;
  height: 40px!important;
  top:0vh;
  border: none !important;
}

.item-carousel div,
.item-carousel button{
  height: 40px;
  width: 70px;
}
.item-carousel div{
  background-size: contain;
  background-repeat: no-repeat;
  background-position: center center;
}

.parameter-option{
  margin-right: /* 2%; */0%;
}
.parameters-content{
  font-size: 1.8vh;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
  -webkit-flex-direction: row;
  -ms-flex-direction: row;
  flex-direction: row;
  -webkit-flex-wrap: wrap;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  -webkit-justify-content: flex-start;
  -ms-flex-pack: start;
  justify-content: flex-start;
  -webkit-align-content: stretch;
  -ms-flex-line-pack: stretch;
  align-content: stretch;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
}
.parameters-content button,
.parameters-content select,
.parameters-content input{
  font-size: 1.5vh;
}
p.show-code{
  color: #ab2300;
}
p{
  font-size: 1.8vh;
}

:host carousel-component.style-carousel.ready .item-carousel{
  -webkit-transition: all 500ms !important;
  -moz-transition:all 500ms!important;
  -o-transition: all 500ms!important;
  transition: all 500ms!important;
}
:host carousel-component.style-carousel.ready .item-carousel.actual{
  height: 40px!important;
  /* top:-2.5vh; */
  width: 100px !important;
  z-index: 2 !important;
  opacity: 1 !important;
  /* transform: translateZ(4px) !important; */
}

:host carousel-component.style-carousel.ready .item-carousel.prev{
    margin-top: 6.75% !important;
    height: 35px!important;
    /* top:-2.5vh; */
    width: 100px !important;
    z-index: 1 !important;
  opacity: 0.3 !important;
  }
:host carousel-component.style-carousel.ready .item-carousel .prev:last-child{
    margin-top: 6.75% !important;
    height: 35px!important;
    /* top:-2.5vh; */
    width: 100px !important;
    z-index: 1 !important;
  opacity: 0.5 !important;
  }
  :host carousel-component.style-carousel.ready .item-carousel.next{
    margin-top: 6.75% !important;
  height: 35px!important;
  /* top:-2.5vh; */
  width: 100px !important;
  z-index: 1 !important;
  opacity: 0.3 !important;
}
  :host carousel-component.style-carousel.ready .item-carousel .next:first-child{
      margin-top: 6.75% !important;
    height: 35px!important;
    /* top:-2.5vh; */
    width: 100px !important;
    z-index: 1 !important;
    opacity: 0.5 !important;
  }
:host carousel-component.cube-mode.ready >>> .container{
  perspective: 10%!important;
}
/* :host carousel-component .container{
    width: 100px!important;
    width: 40px!important;
  } */
/* Small devices (tablets, 768px and up) */
@media (min-width: 768px) {
  h1{
    font-size: 2.5vh;
  }
  .button-toggle,
  p{
    font-size: 1.7vh;
  }
  .parameters-content {
    font-size: 1.7vh;
  }

}

/* Large devices (large desktops, 1200px and up) */
@media (min-width: 1200px) {
  :host carousel-component{
    width: 100px;
  }
  h1{
    font-size: 2.7vh;
  }
  .button-toggle{
    font-size: 1.6vh;
  }

}
@media (min-width: 2000px) {
  :host carousel-component.cube-mode.ready >>> .container{
    perspective: 15%!important;
  }
  .item-carousel{
    width: 100px!important;
    height: 40px!important;
  }
}
.container .carousel .item-carousel {
    border: none !important;
}

`

**Comment by kappys1** [comment]
![Alternate image text](https://i.imgur.com/WaDnEmV.png)
You should to review the code, the css is wrong, you should close this tag **:host carousel-component.style-carousel.ready .item-carousel.prev**
and in the HTML the last button the closed is wrong too 

thanks for use angular-carousel and if you like the library, give me star for help me ;)

**Comment by sruthivarghese15** [comment]
I'm not getting, what's wrong? After resizing it's working fine. Like if u press F12

**Comment by kappys1** [comment]
When I copy your code in my test, I see that you have two sintax error.
One in css:
![image](https://user-images.githubusercontent.com/12160420/41473849-c10d4ee6-70ba-11e8-8657-fa79e8b63bf0.png)
You don't close **:host carousel-component.style-carousel.ready .item-carousel.prev**

one error in html:
![image](https://user-images.githubusercontent.com/12160420/41473832-b5aaf058-70ba-11e8-9138-0178e989c047.png)
separe the button

First, solve this errors and say me if this is the solution... I can't replay your error because for me, solving this errors your code work fine

**Comment by sruthivarghese15** [comment]
Yeah maybe when I copied the code some error occurred.. But there are not syntax errors in the code. Only thing is the width and height of the container is coming as 0px initially.

**Comment by kappys1** [comment]
I don't find your error, for me everything is okay!
Is possible that when you overwrite the library css, you are doing something that the library doesn't work fine...
I recommend that reset your css style and check if this work fine, and forward incrementally your style for find your error...

**Comment by sruthivarghese15** [comment]
Initially also when I was not overriding the css the issue was there. I think it's some initialization issues. As I said the container that is created dynamically is showing width and height as 0px.

**Comment by kappys1** [comment]
Okey!
You don’t said me that your carousel was dinamic, in the documentation I have a dinamically  example:

https://github.com/kappys1/angular2-carousel/tree/web-doc/src/app/components/simple-carousel-from-service

I know that is not the best way but in the next releases I will improve this for don’t reset the carousel

Thanks for say me the bug!!

**Comment by sruthivarghese15** [comment]
Yeah Thanks. It's solved. I knew it was some initialization issue

**Comment by sruthivarghese15** [comment]
But as you can see the actual class button which is the center one is overlapped by other ones when I reduce the margin. Is there any way to overcome this?

**Comment by kappys1** [comment]
Your margin param in the directive is negative, can to try to change for positive number.

And in the new version, the reInit when you add dynamic content is nor required now!

Thanks
